name: HR System CI/CD

on:
  push:
    branches: ["master"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Free disk space (IMPORTANT)
      run: |
        sudo rm -rf /usr/local/lib/android || true
        sudo rm -rf /opt/hostedtoolcache || true
        docker system prune -af || true
        df -h

    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ vars.EC2_HOST }}
        username: ${{ vars.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        debug: true
        script: |
          set -e

          if [ -d "hr-system-devops" ]; then
            cd hr-system-devops
            git pull origin master
          else
            git clone https://github.com/mostafabadie/hr-system-devops.git
            cd hr-system-devops
          fi

          docker compose down || true
          docker compose down --volumes || true
          docker image prune -af || true

          docker compose build --no-cache
          docker compose up -d